# name: rome-format
# on: [push]
# jobs:
#   rome-format:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: rome/setup-rome@v0.1
#         with:
#           version: 0.5.0
#       - uses: actions/checkout@v2
#       - run: rome format --ci --line-width 120 --quote-style single src/
